education_platform/apps/accounts/urls.py
from typing import List

from django.urls import URLPattern, path

from . import views

app_name: str = "accounts"

urlpatterns: List[URLPattern] = [
    path("signout/", views.SignOutView.as_view(), name="signout"),
    path("signin/", views.SignInView.as_view(), name="signin"),
    path("signup/", views.SignUpView.as_view(), name="signup"),
]

education_platform/apps/catalog/urls.py
from typing import List

from django.urls import URLPattern

app_name: str = "catalog"

urlpatterns: List[URLPattern] = []

education_platform/apps/core/urls.py
from typing import List

from django.urls import URLPattern

app_name: str = "core"

urlpatterns: List[URLPattern] = []

education_platform/apps/info/urls.py
from typing import List

from django.urls import URLPattern, path

from . import views

app_name: str = "info"

urlpatterns: List[URLPattern] = [
    path("about_project/", views.AboutProjectView.as_view(), name="about_project"),
    path("about_team/", views.AboutTeamView.as_view(), name="about_team"),
    path("policy/", views.PolicyView.as_view(), name="policy"),
    path("terms/", views.TermsView.as_view(), name="terms"),
]

education_platform/config/urls.py
from typing import Any, List

from debug_toolbar.toolbar import debug_toolbar_urls
from django.conf import settings
from django.contrib import admin
from django.urls import include, path

urlpatterns: List[Any] = [
    path("admin/", admin.site.urls),
    path("", include("education_platform.apps.core.urls", namespace="core")),
    path(
        "info/",
        include("education_platform.apps.info.urls", namespace="info"),
        name="info",
    ),
    path(
        "accounts/",
        include("education_platform.apps.accounts.urls", namespace="accounts"),
        name="accounts",
    ),
    path(
        "catalog/",
        include("education_platform.apps.catalog.urls", namespace="catalog"),
        name="catalog",
    ),
]

if settings.DEBUG:
    urlpatterns += debug_toolbar_urls()

education_platform/apps/accounts/models.py
from django.contrib.auth.models import AbstractUser
from django.core.validators import MinLengthValidator, RegexValidator
from django.db import models


class User(AbstractUser):
    email: models.EmailField = models.EmailField(
        unique=True,
        help_text="Email обязателен для заполнения.",
    )
    username: models.CharField = models.CharField(
        verbose_name="имя пользователя",
        max_length=20,
        unique=True,
        help_text="Имя пользователя обязательно для заполнения.",
        validators=[
            RegexValidator(
                regex=r"^[a-zA-Z0-9_]+$",
                message="Имя пользователя может содержать только латинские буквы, цифры и _.",
                code="invalid_username",
            ),
            MinLengthValidator(
                4, "Имя пользователя должно содержать минимум 4 символа."
            ),
        ],
        error_messages={
            "unique": "Пользователь с таким именем пользователя уже существует.",
            "min_length": "Имя пользователя должно содержать минимум 4 символа.",
            "max_length": "Имя пользователя не может превышать 20 символов.",
        },
    )

education_platform/apps/accounts/forms.py
from django import forms
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import AuthenticationForm, UserCreationForm


class SignInForm(AuthenticationForm):
    """Форма для входа в аккаунт."""

    class Meta:
        model = get_user_model()
        fields: tuple = ("username", "password")


class SignUpForm(UserCreationForm):
    """Форма для регистрации нового пользователя."""

    first_name: forms.CharField = forms.CharField(
        required=True,
        error_messages={
            "required": "Имя обязательно для заполнения.",
        },
        label="Имя",
    )
    last_name: forms.CharField = forms.CharField(
        required=True,
        error_messages={
            "required": "Фамилия обязательна для заполнения.",
        },
        label="Фамилия",
    )
    email: forms.EmailField = forms.EmailField(
        required=True,
        error_messages={
            "required": "Email обязателен для заполнения.",
            "invalid": "Некорректный email, попробуйте еще раз.",
            "unique": "Пользователь с таким email уже существует.",
        },
        label="Email",
    )
    username: forms.CharField = forms.CharField(
        required=True,
        error_messages={
            "required": "Имя пользователя обязательно для заполнения.",
            "unique": "Пользователь с таким именем пользователя уже существует.",
        },
        label="Имя пользователя",
    )
    password1: forms.CharField = forms.CharField(
        required=True,
        error_messages={
            "required": "Пароль обязателен для заполнения.",
            "invalid": "Некорректный пароль, попробуйте еще раз.",
        },
        label="Пароль",
    )
    password2: forms.CharField = forms.CharField(
        required=True,
        error_messages={
            "required": "Подтверждение пароля обязательно для заполнения.",
            "invalid": "Пароли не совпадают, попробуйте еще раз.",
        },
        label="Подтверждение пароля",
    )

    class Meta:
        model = get_user_model()
        fields: tuple = (
            "first_name",
            "last_name",
            "email",
            "username",
            "password1",
            "password2",
        )

education_platform/apps/accounts/views.py
from django.contrib.auth import login, logout
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth.views import LoginView
from django.core.handlers.wsgi import WSGIRequest
from django.http import HttpResponse
from django.shortcuts import redirect
from django.urls import reverse_lazy
from django.views import View
from django.views.generic import CreateView

from education_platform.apps.accounts.forms import SignInForm, SignUpForm
from education_platform.apps.accounts.mixins import AnonymousRequiredMixin


class SignOutView(View):
    """Представление для выхода из аккаунта."""

    @staticmethod
    def get(request: WSGIRequest) -> HttpResponse:
        logout(request)
        return redirect("info:about_project")


class SignInView(LoginView):
    """Представление для входа в аккаунт."""

    form_class: type[AuthenticationForm] | None = SignInForm
    template_name: str = "accounts/signin.html"
    redirect_authenticated_user: bool = True

    def get_success_url(self) -> str:
        return reverse_lazy("info:about_project")


class SignUpView(AnonymousRequiredMixin, CreateView):
    """Представление для регистрации нового пользователя."""

    form_class: type[SignUpForm] = SignUpForm
    template_name: str = "accounts/signup.html"
    success_url: str = reverse_lazy("info:about_project")

    def form_valid(self, form: SignUpForm) -> HttpResponse:
        response: HttpResponse = super().form_valid(form)
        user = form.instance
        login(self.request, user, backend="django.contrib.auth.backends.ModelBackend")
        return response

education_platform/apps/info/views.py
from django.views.generic import TemplateView


class AboutProjectView(TemplateView):
    """Представление для страницы "О проекте"."""

    template_name: str = "info/about_project.html"


class AboutTeamView(TemplateView):
    """Представление для страницы "О команде"."""

    template_name: str = "info/about_team.html"


class PolicyView(TemplateView):
    """Представление для страницы "Политика конфиденциальности"."""

    template_name: str = "info/policy.html"


class TermsView(TemplateView):
    """Представление для страницы "Пользовательское соглашение"."""

    template_name: str = "info/terms.html"

education_platform/apps/accounts/templates/accounts/signin.html
{% extends 'base.html' %}

{% load static %}

{% block title %}Вход{% endblock %}

{% block css %}
<link rel="stylesheet" href="{% static 'accounts/css/signin.css' %}">
{% endblock %}

{% block content %}
<div class="content__signin">
    <div class="signin__top">
        <h2 class="signin__title">Вход</h2>
    </div>

    <form class="signin__form" action="{% url 'accounts:signin' %}" method="POST">
        {% csrf_token %}

        {% if form.non_field_errors %}
            <div class="signin__errors">
                {{ form.non_field_errors }}
            </div>
        {% endif %}

        <input value="{% if form.username.value %}{{ form.username.value }}{% endif %}" class="signin__input" type="text" name="username" placeholder="Имя пользователя">
        <input class="signin__input" type="password" name="password" placeholder="Пароль">
        <button class="signin__button" type="submit">Войти</button>
    </form>

    <div class="signin__links">
        <a class="signin__link" href="{% url 'accounts:signup' %}">Регистрация</a>
        <a class="signin__link" href="#">Забыли пароль?</a>
    </div>
</div>
{% endblock %}

education_platform/apps/accounts/templates/accounts/signup.html
{% extends 'base.html' %}

{% load static %}

{% block title %}Регистрация{% endblock %}

{% block css %}
<link rel="stylesheet" href="{% static 'accounts/css/signup.css' %}">
{% endblock %}

{% block content %}
<div class="content__signup">
    <div class="signup__top">
        <h2 class="signup__title">Регистрация</h2>
    </div>

    <form class="signup__form" action="{% url 'accounts:signup' %}" method="POST">
        {% csrf_token %}

        {% if form.non_field_errors %}
            <div class="signup__errors">
                {{ form.non_field_errors }}
            </div>
        {% endif %}

        {% for field in form %}
            {% if field.name == 'password1' or field.name == 'password2' %}

            {% else %}
                {{ field.errors }}
                <input {% if field.value %}value="{{ field.value }}"{% endif %} class="signup__input" type="text" name="{{ field.name }}" placeholder="{{ field.label }}">
            {% endif %}
        {% endfor %}

        {{ form.password1.errors|add:form.password2.errors }}
        <input class="signup__input" type="password" name="password1" placeholder="Пароль">
        <input class="signup__input" type="password" name="password2" placeholder="Подтверждение пароля">
        <button class="signup__button" type="submit">Зарегистрироваться</button>
    </form>

    <div class="signup__links">
        <a class="signup__link" href="{% url 'accounts:signin' %}">Уже есть аккаунт?</a>
    </div>
</div>
{% endblock %}

education_platform/apps/info/templates/info/about_project.html
{% extends 'base.html' %}

{% load static %}

{% block title %}О проекте{% endblock %}

{% block css %}
<link rel="stylesheet" href="{% static 'info/css/about_project.css' %}">
{% endblock %}

{% block content %}
<div class="content__description">
    <p class="description__text"><span class="description__highlighting">“MindMotion” — </span>инновационная
        образовательная IT-платформа объединяющая современное обучение и искусственный интеллект. Платформа предлагает
        структурированные курсы, в которых содержится теория, а также практические задачи на ее закрепление. После
        выполнения ИИ анализирует решение, проверяет соответствие лучшим практикам и дает персонализированные
        рекомендации по улучшению решения. Также ИИ может мотивировать обучающегося при выполнении задачи. После
        успешного прохождение курса пользователь получает уникальный сертификат.</p>
    <p class="description__purpose"><span class="description__highlighting">Цель проекта — </span>повышение качества
        IT-образования в России.</p>
    <p class="description__audience"><span class="description__highlighting">Целевая аудитория — </span>новички и
        профессионалы желающие развиваться в IT.</p>
    <p><span class="description__highlighting">Уникальные особенности:</span></p>
    <ul class="description__uniqueness-list">
        <li class="description__uniqueness-item"><span class="description__highlighting">Использование ИИ для анализа решения:</span> С первых шагов в
            программировании обучающиеся получают мгновенную обратную связь от искусственного интеллекта. Это позволяет
            сразу исправлять ошибки, оптимизировать код и применять лучшие практики.</li>
        <li class="description__uniqueness-item"><span class="description__highlighting">Обучение через улучшение, а не просто
                "правильно/неправильно":</span> Вместо стандартной проверки на соответствие тестам, ИИ разбирает логику,
            архитектуру и стиль кода, объясняя, как сделать решение эффективнее. Так студенты учатся не просто
            "проходить задания", а писать код, как Senior разработчики.</li>
        <li class="description__uniqueness-item"><span class="description__highlighting">Персонализированные рекомендации:</span> Алгоритмы адаптируются под
            уровень пользователя: новичкам дают больше пояснений по основам, а опытным — углубленную аналитику по
            оптимизации.</li>
        <li class="description__uniqueness-item"><span class="description__highlighting">Профилактика "слепого копирования":</span> Даже если решение
            технически верное, ИИ покажет, где можно применить более элегантные подходы, предотвращая механическое
            заучивание.</li>
        <li class="description__uniqueness-item"><span class="description__highlighting">Мотивация от ИИ:</span> При решении задачи, ИИ выдает мотивационные
            фразы, что способствует не сдаваться.</li>
    </ul>
</div>
{% endblock %}

education_platform/apps/info/templates/info/about_team.html
{% extends 'base.html' %}

{% load static %}

{% block title %}О команде{% endblock %}

{% block css %}
<link rel="stylesheet" href="{% static 'info/css/about_team.css' %}">
{% endblock %}

{% block content %}
<div class="content__participants">
    <div class="participant">
        <img class="participant__img" src="{% static 'info/img/team/potemkina_anna_alekseevna.png' %}"
            alt="Потемкина Анна Алексеевна">
        <h2 class="participant__name">Потемкина<br>Анна Алексеевна</h2>
        <p class="participant__role">Designer & Compliance Specialist</p>
    </div>
    <div class="participant">
        <img class="participant__img" src="{% static 'info/img/team/tokarev_denis_alexandrovich.png' %}"
            alt="Токарев Денис Александрович">
        <h2 class="participant__name">Токарев<br>Денис Александрович</h2>
        <p class="participant__role">Developer & TeamLead</p>
    </div>
    <div class="participant">
        <img class="participant__img" src="{% static 'info/img/team/shashina_ksenia_evgenieva.png' %}"
            alt="Шашина Ксения Евгеньевна">
        <h2 class="participant__name">Шашина<br>Ксения Евгеньевна</h2>
        <p class="participant__role">Designer & Speaker</p>
    </div>
</div>
{% endblock %}

education_platform/apps/info/templates/info/policy.html
{% extends 'base.html' %}

{% load static %}

{% block title %}Политика конфиденциальности{% endblock %}

{% block css %}
<link rel="stylesheet" href="{% static 'info/css/policy.css' %}">
{% endblock %}

{% block content %}
<h1> Политика конфиденциальности </h1>
{% endblock %}

education_platform/apps/info/templates/info/terms.html
{% extends 'base.html' %}

{% load static %}

{% block title %}Пользовательское соглашение{% endblock %}

{% block css %}
<link rel="stylesheet" href="{% static 'info/css/terms.css' %}">
{% endblock %}

{% block content %}
<h1>Пользовательское соглашение</h1>
{% endblock %}

education_platform/templates/base.html
<!doctype html>

{% load static %}

<html lang="ru">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>MindMotion - {% block title %}{% endblock %}</title>
    <link rel="stylesheet" href="{% static 'css/reset.css' %}">
    <link rel="stylesheet" href="{% static 'css/header.css' %}">
    <link rel="stylesheet" href="{% static 'css/footer.css' %}">
    <link rel="stylesheet" href="{% static 'css/base_style.css' %}">
    <link rel="icon" href="{% static 'img/favicon.ico' %}">
    {% block css %}{% endblock %}
</head>
<body>
    <div id="root">
        {% include 'includes/header.html' %}
        <div class="content">{% block content %}{% endblock %}</div>
        {% include 'includes/footer.html' %}
    </div>
</body>
</html>

education_platform/templates/includes/footer.html
<footer>
    <div class="footer__chapters">
        <div class="footer__chapter">
            <h2 class="footer__chapter_title">Правила</h2>
            <a class="footer__chapter_link" href="{% url 'info:policy' %}">Политика конфиденциальности</a>
            <a class="footer__chapter_link" href="{% url 'info:terms' %}">Пользовательское соглашение</a>
        </div>
        <div class="footer__chapter">
            <h2 class="footer__chapter_title">Проект</h2>
            <a class="footer__chapter_link" href="{% url 'info:about_project' %}">О проекте</a>
            <a class="footer__chapter_link" href="{% url 'info:about_team' %}">О команде</a>
        </div>
        <div class="footer__chapter">
            <h2 class="footer__chapter_title">Контакты</h2>
            <a class="footer__chapter_link" href="mailto:wf.denis.tokarev@gmail.com">wf.denis.tokarev@gmail.com</a>
            <a class="footer__chapter_link" href="tel:+79644102006">+7 (964) 410-20-06</a>
        </div>
    </div>
</footer>

education_platform/templates/includes/header.html
{% load static %}

<header>
    <h1><img class="header__logo" src="{% static 'img/logo.svg' %}" alt="MindMotion"></h1>
    <div class="header__controls">
        <input class="header__input" type="text" placeholder="Поиск..." aria-label="Поиск">
        <div class="header__user">
            {% if request.user.is_authenticated %}
                <a href="#" role="button">{{ request.user.username }}</a>
                <a href="{% url 'accounts:signout' %}" role="button">Выйти</a>
            {% else %}
                <a href="{% url 'accounts:signin' %}" role="button">Войти</a>
            {% endif %}
        </div>
    </div>
</header>